apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ams-auto-sdb
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auto-sdb.aaronschweig.dev`)
      kind: Rule
      services:
        - name: ams-auto-sdb
          port: 3000
  tls:
    certResolver: cloudflare